[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stdapi"
version = "1.0.1"
description = "Next-gen asynchronous SDK & CLI for unified Media, AI, Search, and Bot automation."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "Apache-2.0" }

authors = [
  { name = "STD-DEEPANSHU", email = "support@deepanshu.in" }
]

keywords = [
  "api",
  "sdk",
  "telegram-bot",
  "downloader",
  "media",
  "ai",
  "search",
  "cli"
]

dependencies = [
  "aiohttp>=3.9.0",
  "requests>=2.31.0"
]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Software Development :: Libraries :: Python Modules"
]

[project.scripts]
stdapi = "stdapi.cli:main"

[project.urls]
Homepage = "https://github.com/STD-DEEPANSHU/StdAPI"
Documentation = "https://github.com/STD-DEEPANSHU/StdAPI#readme"
Tracker = "https://github.com/STD-DEEPANSHU/StdAPI/issues"
